### ISSUE TITLE
Remove functions for command errors

### ISSUE THREAD

**Issue by LeptoSpira** [DrBluefall/ProjectPrismarine#11]
As an example:
```python
    @commands.has_permissions(manage_messages=True)
    @mod.command()
    async def delete(self, ctx, amount: int = 10):
        """
        Purge a number of messages.

        Parameters:
            - Amount (Integer): Number of messages to delete.

        Returns:
            - A message displaying the number of deleted messages. Deletes itself after 10 seconds.

        Will not work if:
            - The command user does not have the `manage messages` permission.

        """
        channel = self.client.get_channel(ctx.channel.id)
        deleted = await channel.purge(limit=amount)
        await ctx.send(
            f"{len(deleted)} message(s) have been deleted.", delete_after=10
        )

    @delete.error
    async def delete_error(self, ctx, error):
        """Error when delete doesn't work."""
        if isinstance(error, commands.MissingPermissions):
            await ctx.send(
                "Command failed. Make sure you have the `manage_messages` permission in order to use this command."
            )
```
This totally destroys readability because it implies that the error catcher and the command itself are on the same levels if we just use a try except, or an if statement, it would be much better. Plus, it would be consistent with the other modules.

**Comment by DrBluefall** [comment]
See, we can't do that because of how the check decorator works. It raises an error before it runs the command if the user fails to pass the check, so the command would never get to the `try/except` in the first place. And yes, whilst it is a bit harder to read, and it's a tad inconsistent, it's just the nature of how the check decorators function.

**Comment by DrBluefall** [comment]
NEVERMIND, I'M JUST STUPID. I went through the docs for discord.py and found a way to check permissions without the decorators, although it uses one beastly if statement. This issue can proceed with being addressed!

**Comment by DrBluefall** [comment]
Alright, all the error functions have been removed. Issue solved!
