### ISSUE TITLE
Implement Git Workflow.

### ISSUE THREAD

**Issue by LeptoSpira** [DrBluefall/ProjectPrismarine#13]
# Situation
We have designed a git workflow to fit our needs, and need to implement it
# Workflow description:
![Workflow Image](https://media.discordapp.net/attachments/583121031108231211/594333848813436941/git-model2x.png?width=516&height=683)
Topic branches are on origin as well, this allows multiple developers to work on a feature together, a crucial part of me, and @DrBluefall's system. This also allows it to scale well. We are calling it topics instead of features to further hint at its remote presence.

The develop branch will be called `develop-canary`, because it is tested on the `Prismarine Canary` bot. This is just for fun, there isn't any nightly build.

# Implementation
- [x] Our first priority is to [Impliment the loadout feature](https://github.com/DrBluefall/ProjectPrismarine/issues/2) on the `canary` branch.
- [x] @LeptoSpira Replace `origin/canary` with `origin/develop-canary`
  - [x] Pull `origin/canary` branch to `develop-canary`
  - [x] Delete  `origin/canary` branch
  - [x] Publish `develop-canary` to new `origin/develop-canary`
- [x] Then, we will create a new branch `topics/composer` for the [Composer Cog](https://github.com/DrBluefall/ProjectPrismarine/issues/12)
- [x] We will merge `develop-canary` into `master` & `topics/composer`
- After this, all 3 branches should be up to date.
- [x] The `hotfixes` branch will be created, up to date as well.
- [x] Review to make sure all branches are created at this point:
  ```
  master
  develop-canary
  hotfixes
  topics (folder)
    composer
  ```
- This marks the beginning of the implementation of the workflow
- [x] Profit! These are the steps to implementing the workflow!

**Comment by DrBluefall** [comment]
All tasks complete and branches created. We can start using this workflow now!

**Comment by LeptoSpira** [comment]
Looks like loadout is still not implemented fully, there are still some things that need to be worked out.

**Comment by DrBluefall** [comment]
Ok, the loadout issue should be *safely* in place now, after a bit of testing. Closing time!
