### ISSUE TITLE
Make table queries more explicit.

### ISSUE THREAD

**Issue by LeptoSpira** [DrBluefall/ProjectPrismarine#14]
Right now the table queries are very implicit:
`table.c.class_id`
What does c mean? It means columns.

This needs to be changed to `table.columns.class_id`, At it is more explicit.
It is also ambiguous to the connection variable `self.c` which also needs to be changed. and can be abstracted to `self.database` or the likes, since the connection is the only database return we actually use.

**Comment by LeptoSpira** [comment]
### Tangent:

The database connecting is inconsistent
```
    engine = create_engine("sqlite:///ProjectPrismarine.db")
    metadata = MetaData(engine)
    table = Table(
        "profile",
        metadata,
        Column("user_id", Integer, primary_key=True),
        ...
    )

    metadata.create_all()
    c = engine.connect()
```

```
db = create_engine("sqlite:///main.db")
metadata = MetaData(db)
metadata.reflect()
c = db.connect()
```

```
    db = create_engine("sqlite:///main.db")
    metadata = MetaData(db)
    prefix_table = Table(
        "prefix", metadata, Column("server_id", Integer, primary_key=True),
        Column("prefix", String)
    )

    metadata.create_all()
    c = db.connect()
```
This needs to be consistant.
And that is all.

**Comment by DrBluefall** [comment]
Wait...about that tangent, where did you find that first code snippet?

**Comment by LeptoSpira** [comment]
Another thing, change all times `c` is used for columns, to `columns`.

**Comment by LeptoSpira** [comment]
Another thing, change `columns.key` to `columns["key"]`
