### ISSUE TITLE
Loadout screw-up with splatnet

### ISSUE THREAD

**Issue by LeptoSpira** [DrBluefall/ProjectPrismarine#15]
# Situation
Post merge, with the current `develop-canary` branch is busted. This is caused by my debodge of the `splatnet.py` file causing errors. Pre-merge (at least what @DrBluefall has told me) which is with the current `master` branch should be working.
# Steps to fix
- [ ] First, check to see if the master branch does work as intended
  - [ ] If it does not, reset master (and the branches with it) to the latest commit that it does work.
- [ ] Checkout to `develop-canary` the branch after this issue has happened, and work on fixing the splatnet.py screw-up.
- [ ] After that has been done, fast-forward master (and the branches with it) back up to `develop-canary`.
- [ ] Then go back to [implementing the git workflow](https://github.com/DrBluefall/ProjectPrismarine/issues/13)

**Comment by DrBluefall** [comment]
Ok, a few...*interesting* notes.

It looks like the latest version of `master`, after being merged with `develop-canary`, is functional! I don't know what went wrong last night, but for some reason it works now! I'll try to get the bot functional on GCP. Once that happens, I'll close the issue.

**Comment by DrBluefall** [comment]
Ok, the `master` branch is live on GCP! I'll keep an SSH tab open and monitor for any issues. If anything happens, I'll comment here. Otherwise, I *think* we can safely close this issue.
