### ISSUE TITLE
Change SQLAlchemy to ORM

### ISSUE THREAD

**Issue by LeptoSpira** [DrBluefall/ProjectPrismarine#18]
Python is object-oriented, and sqlalchemy should be the same.

There aren't a lot of details right now, comments with more might come.

**Comment by DrBluefall** [comment]
I have a feeling that a lot of problems that we're having right now can be dealt with easier if we go though with the ORM rework. I'm increasing this issue's priority.

**Comment by DrBluefall** [comment]
OK, update: SQLAlchemy is being scrapped entirely. No point in keeping this open.
