### ISSUE TITLE
File Directory Rework

### ISSUE THREAD

**Issue by DrBluefall** [DrBluefall/ProjectPrismarine#19]

**Comment by LeptoSpira** [comment]
- [ ] There are way too many imports

**Comment by LeptoSpira** [comment]
- [ ] Bin is not used correctly

**Comment by LeptoSpira** [comment]
- [ ] No utils folder/file

**Comment by LeptoSpira** [comment]
- [ ] No common folder/file

**Comment by LeptoSpira** [comment]
Files are too long, it takes a while to scroll through it.
