### ISSUE TITLE
What happened to the submodules?

### ISSUE THREAD

**Issue by LeptoSpira** [DrBluefall/ProjectPrismarine#24]
## Origins
Originally what I had planned (before I became an unofficial developer) was to have a `PrismarineCog` class, which is subclassed from _instead_ of subclassing from commands.cog, meaning we do not need to actually import that.

This was going to be extended upon by then importing the submodules directory, which holds the database handler class and so on. This way, the `PrismarineCog` class will import all submodules and create a new template cog. This was, in essence, replacing the "templates"  folder in the soon-to-by legacy version.

## Relative File Directory / Usage
Here is a basic idea of the relative file directory
```md
- utils
- template_module
    - template_module.py (contains TemplateModule, imports submodules)
    - submodules
        - db_handler (contains DatabaseHandler)
        - template_cog (contains TemplateCog, which creates help function etc.) 
```
So in order for you to use this template module in a module, for example, you would do:
```py
from utils.template_module import TemplateModule

class MyModuleEample(TemplateModule):
    # And as such, this would be the only subclass used.
```
## Benefits?
Some of the benefits to this are less importing needs to be done (you only need to import a single template module to have access to all the tools necessary)

This also allows easy change to any aspect of the template module without needing to scroll through the file, the database handler needs a fix? Right there, immediately affecting any modules, and fixing the bug universally.

## Potential Drawbacks / Critiques and Workarounds / Rebuttals
> ### There are too many files and folders!

I find this not an issue, in fact, I find it more of a positive. Code is:
- Cleaner
- Easier to read
- Easier to navigate

There is also:
- Less scrolling = more happiness
- (It also looks good on the repo statistics :wink: )

> ### Why would we need a template_cog instead of just handling it inside of the template_module.py file?

I like to think of the discord cog part of the module, an equal player with any other part of the cog. On the same level as the database handler.

This, again _also_ makes it much easier to change just a specific discord related part to the bot.

Let's say you want to render the help command differently. Instead of going to the template cog and having to view all the imports and subclassing, you simply only see the discord cog part. Abstracting the use of the template cog, and anything.

> ### I don't like the name of \_\___ can I change it?.

That's _totally_ fine, this was more of an example of what potential names might be. I, of course, incorporated the current state of the repo in with the example to illustrate a possible use case.

**Comment by LeptoSpira** [comment]
> ### `self.dbh = DatabaseHandler()`
> *This line of code is the bane of Lepto's existence.*

**Comment by DrBluefall** [comment]
Ok, time for the Dissenting Opinion:

***I believe that the initially planned module base is pointless.***

Now, why you may ask? To that, I propose a counter-question: *what purpose would the module base serve?* Beyond just tacking on a help command (which can be done better via an implementation detailed in [the discord.py docs](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#help-commands)), what other functionality could the module base serve?

What is the practical difference of doing this:
`class Foo(commands.Cog, DatabaseHandler):`
versus this?
```python
class Foo(commands.Cog):

    def __init__(self, client):
        self.client = client
        self.dbh = DatabaseHandler()
```

Yes, what your describing sounds nice *in theory*, but *in practice*, would it be of any practical use? 

~~also I tried to use the first method, didn't work feelsbadman~~

**Comment by LeptoSpira** [comment]
# Practical Differences
## Usage
Instead of doing 
`self.dbh.update_sw()`
you just do
`self.update_sw()`

You are also minimizing the number of self variables.

## Class Defining:
Why did I **clearly** emphasized **not** doing `class Foo(commands.Cog, DatabaseHandler):`
and instead, go for `class Foo(ModuleBase):`

### It is scalable and makes it much simpler to subclass from. Here's why:

Let's say not only do we need a database handler but some other arbitrary submodule.
We would have to do:
`class Foo(commands.Cog, DatabaseHandler, SomeArbritrarySubmodule):`
This would get large quickly. As we already see with this:
```python
class ServerConfig(
    commands.Cog,
    name="Server Configuration",
    command_attrs=dict(
        checks=[
            commands.has_permissions(administrator=True),
            commands.guild_only()])):
```
It also makes it harder to edit the Discord Cog element of the module base if we have it incorporated into the module base directly. Since you have to scroll through irrelevant code to get to it.

* * *

This outlines most of the practical usage of it.
And what do you mean by trying the first method and it not working? The solution isn't to drop it, but to figure out why it doesn't work.

**Comment by DrBluefall** [comment]
I mean...if I *really* wanted to minimize the number of imports, I could import the `DatabaseHandler` into the core file and set it as a self variable of the `Client` class. Not something I intend to do (at least, not right now), but I'm just taking this statement:
```You are also minimizing the number of self variables.```
And viewing it from its logical extreme.

And with regards to adding some arbitrary module...what would there be to add? What functionality would need to be implemented across *every single module* the bot has, that can't just be done on a case-by-case basis? Modules should only have to import the absolute necessities for their functionality, and not a single line of code more. Importing unnecessary functionality for a module just doesn't sit well with me. So classes should only subclass any functionality they need. If they need database interaction? Subclass `DatabaseHandler`. Needs dinosaurs? Subclass dinosaurs. Just need to make a cog? Subclass `commands.Cog` and be done with it. I'd say that this is more efficient.

**Comment by LeptoSpira** [comment]
But you aren't subclassing database handlers. You are creating a self variable.
