### ISSUE TITLE
change weapons to be class with weapon subclass

### ISSUE THREAD

**Issue by LeptoSpira** [DrBluefall/ProjectPrismarine#7]
Classes are a thing and the current way we have set up the database makes it inconsistent to deal with them, in order to make it consistent, we should have a class table with weapon subclasses.

##### **Some Reasons:**
- We need a loadout.ink and normal ID because of the loadout.ink one is only unique for each class
- class_id makes no sense to be inside of a weapons table
- subclasses are cool

**Comment by DrBluefall** [comment]
This will be addressed in a future project TBC. I'll close this issue.
