### ISSUE TITLE
 replaced `core.py` comments with classes

### ISSUE THREAD

**Issue by LeptoSpira** [DrBluefall/ProjectPrismarine#8]
Inside of `core.py` you have these comments:
```python
# --- Client Events
```
```python
# --- Bot Commands
```
Changing this to a class:
```python
class ClientEvents:
```
```python
class BotCommands:
```

**Comment by DrBluefall** [comment]
Well, I have good news and bad news.

The good news:
- I moved the core commands into `misc.py`, shortening `core.py` massively.

The bad news:
- The listeners and misc code could not be moved into classes.

So, that's where this story is for now. Until we find something new, I'll close this issue.
